/**
 *
 */

package com.nsfc.platform.userinfo.model;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userInfo
 * @Edit_Description:
 * @Create_Version:shebao-order-model 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2018-04-17 15:50:10
 */
public class UserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.id
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.username
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.password
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.ages
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private Integer ages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.gender
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.mobilePhone
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.email
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.id
     *
     * @return the value of userInfo.id
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.id
     *
     * @param id the value for userInfo.id
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.username
     *
     * @return the value of userInfo.username
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.username
     *
     * @param username the value for userInfo.username
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.password
     *
     * @return the value of userInfo.password
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.password
     *
     * @param password the value for userInfo.password
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.ages
     *
     * @return the value of userInfo.ages
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public Integer getAges() {
        return ages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.ages
     *
     * @param ages the value for userInfo.ages
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setAges(Integer ages) {
        this.ages = ages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.gender
     *
     * @return the value of userInfo.gender
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.gender
     *
     * @param gender the value for userInfo.gender
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.mobilePhone
     *
     * @return the value of userInfo.mobilePhone
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.mobilePhone
     *
     * @param mobilephone the value for userInfo.mobilePhone
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.email
     *
     * @return the value of userInfo.email
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.email
     *
     * @param email the value for userInfo.email
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}