/**
 *
 */

package com.nsfc.platform.userinfo.mapper;

import com.nsfc.platform.userinfo.model.UserInfo;
import com.nsfc.platform.userinfo.model.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userInfo
 * @Edit_Description:
 * @Create_Version:shebao-order-model 1.0
 *
 * @mbg.generated do_not_delete_during_merge 2018-04-17 15:50:10
 */
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     * @Edit_Description:
     * @Create_Version:shebao-order-model 1.0
     *
     * @mbg.generated 2018-04-17 15:50:10
     */
    int updateByPrimaryKey(UserInfo record);
}